title:            David P. Larson
#Comment out url when working locally to resolve base urls correctly
url:             http://ieng6.ucsd.edu/~dplarson 

# Owner/author information
owner:
  name:           David P. Larson
  avatar:         David_Larson.jpg
  email:          dplarson@ucsd.edu
  github:         "dplarson"
  linkedin:       "http://www.linkedin.com/pub/david-larson/65/334/934"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-36350691-1

timezone:    America/Los_Angeles
future:      true
#highlighter: true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["bin", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "Gemfile", "Gemfile.lock", "LICENSE", "script"]
