---
baseurl: "http://ieng6.ucsd.edu/~dplarson/"
title: "David P. Larson"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
params:
    AuthorName: "David P. Larson"
    GoogleAnalytics: "UA-36350691-1"
---
