---
baseurl: "http://ieng6.ucsd.edu/~dplarson/"
title: "David P. Larson"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
params:
    author: "David P. Larson"
    googleanalytics: "UA-36350691-1"
---
