mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: David P. Larson 
        author:
            name: David P. Larson 
            url: "http://ieng6.ucsd.edu/~dplarson/"
        hyde:
            name: Hyde
            url: "http://hyde.github.com"
        bootstrap:
            name: Bootstrap
            url: "http://twitter.github.com/bootstrap/"
        google_analytics_id: UA-XXXXX-YY
        home_url: index.html
        menu:
            - title: About
              url: index.html
            - title: Research
              url: research.html
            - title: Media
              url: media.html
